### ISSUE TITLE
Rename "backup/restore visible" menu items to something else?

### ISSUE THREAD

**Issue by vanowm** [vanowm/FirefoxCookiesManagerPlus#103]
"Backup visible" can be incorrectly interpreted as "visible on screen" instead of "shown in the list".
This backup method will export cookies that are shown by filter/search, so another name needed.

For now I'm leaning towards "Backup shown" with a tooltip text "Backup currently shown in the list"

Any other suggestions?

**Comment by BzSpi** [comment]
How about "Backup this list" or "Backup this filtered list" ?

**Comment by Atavic** [comment]
Selected Backup?
Backup Selection?

**Comment by vanowm** [comment]
I'll leave it as "Backup shown", because in the title is shows "showing 123 of 1234, selected 1"
