### ISSUE TITLE
Master p/w prompt on startup v1.10+

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [vanowm/FirefoxCookiesManagerPlus#105]
snip

**Comment by Roman-Nopantski** [comment]
I turned off "enable read only", I disabled "allow websites delete read-only", I even set search history to none. Auto refresh is disabled as well. There is no synchronization with native cookies viewer. Nothing in settings seems to change the behavior on FF start (or on restartless restart). Am at a loss.

**Comment by vanowm** [comment]
Yes, it's because of encryption used by read-only feature.
Explained in #88

**Comment by Roman-Nopantski** [comment]
Thanks :)
