### ISSUE TITLE
Encrypted read-only data lost if user canceled master password

### ISSUE THREAD

**Issue by vanowm** [vanowm/FirefoxCookiesManagerPlus#106]
If read-only encryption is enabled and user canceled master password prompt on startup, the read-only data is lost.

**Comment by vanowm** [comment]
The fix is on it's way, it will prompt for master password (if not yet logged in) during CM+ launch and close and will better handle if user cancels MP prompt.

If there is encrypted read-only data previously saved and master password prompt was canceled, CM+ won't be able decrypt the data and wont show any read-only cookies. The saved data will remain intact until user add any readonly data, at which point it will save in unencrypted format (disregarding user's preferences). If user closes browser, the previously encrypted data will be lost, because it was overwritten by new data, however if user login with master password during same session and relaunch CM+ it will merge currently saved unencrypted data with previously encrypted and save everything as new encrypted data.

**Comment by hooverelectronics** [comment]
anyway vanowm you can put that into simpler form Im new to this whole thing, not sure what cm+ or or mp prompt is.
Im having issues loggin on to own website. also says needs to be encrypted, in which I know not a thing about
