### ISSUE TITLE
Cookie Manger makes Firefox ask me for my Masterpassword on startup

### ISSUE THREAD

**Issue by Przbl** [vanowm/FirefoxCookiesManagerPlus#107]
When Cookie Manger is installed Firefox asks me for my Masterpassword on startup. Why is that? Usually this only happens when a website is opened that has a stored counterpart in the Firefox password manager.

Is Cookie Manager connecting to a website in the background on startup?

**Comment by vanowm** [comment]
Duplicate #88 
Next version will have an option with explanation.
