### ISSUE TITLE
e10s: Mark your addon as compatible

### ISSUE THREAD

**Issue by rugk** [vanowm/FirefoxCookiesManagerPlus#117]
Follow-up of https://github.com/vanowm/FirefoxCookiesManagerPlus/issues/81

According to [ACR](https://addons.mozilla.org/firefox/addon/add-on-compatibility-reporter/) this add-on is not compatible with e10s. You can change the manifest file of your add-on to mark it as compatible with e10s.

**Comment by vanowm** [comment]
It is [enabled](https://github.com/vanowm/FirefoxCookiesManagerPlus/blob/master/src/install.rdf#L18) and it is compatible according to [ACR](https://addons.mozilla.org/en-US/firefox/compatibility/reporter/%7Bbb6bc1bb-f824-4702-90cd-35e2fb24f25d%7D)
