### ISSUE TITLE
Read-Only not working

### ISSUE THREAD

**Issue by SergeGardien** [vanowm/FirefoxCookiesManagerPlus#123]
I've set the content and expiry date of a cookie to read-only but this is reset to read-write soon as I close and reopen Firefox.

I've tried the "Set as default cookies manager" option for Cookies Manager+ with no luck.

How can I fix this issue?

**Comment by vanowm** [comment]
Make sure you disabled Options -> Read-only tab -> Allow websites delete read-only cookies.

**Comment by SergeGardien** [comment]
Thanks for your reply vanowm

That was already disabled.
The cookie didn't get deleted (I haven't re-opened the website generating it) it was simply reset to read-write.

Could it be a conflict with Firefox Cookies Manager?
In Firefox (Preferences => Privacy => History) I've set "Use custom settings for history" and I've specified some exceptions for cookies (I block some websites form storing their cookies but not the website generating the cookie object of the thread)

**Comment by vanowm** [comment]
1. Does this happen only on specific cookie/website?
2. If 1 is true, can test myself?
3. Is there any error messages shown in browser console (CTRL+SHIFT+J) when you enable debug login in CM+ options (you might need restart browser to make sure)?

P.S.
I might need a backup of your settings from CM+ options.

**Comment by SergeGardien** [comment]
1. I've tried with one specific cookie from ft.com and a specific cookie from linkedin.com and both have this issue.
2. Sure, cookie "ft_access_c" from ft.com (just open any ft.com article and you will get it, ex. [ft.com](https://www.ft.com/content/d16c2caa-effa-32f4-a656-6438aec025df)
3. I haven't seen any error in the browser console. This is the log related to the modification from 
   read-write to read-only for the "content" field of the cookie mentioned at point (2):
   `CM+ (cookiesmanagerplus.js:2412:1): (debug):infoRowAction([object MouseEvent]) execTime: 102290`
   `CM+ (coomanPlusCore.jsm:378:1): (debug):readonlyAdd([object Object], true) execTime: 102291`
   `CM+ (coomanPlusCore.jsm:504:1): (debug):readonlySave() execTime: 102292`
   `CM+ (coomanPlusCore.jsm:472:1): (debug):readonlyDecryptEncrypted() execTime: 102293`
   `CM+ (coomanPlusCore.jsm:717:1): (debug):[storage file save begin] storageWrite(undefined, 60000, undefined) execTime: 102295`
   `CM+ (cookiesmanagerplus.js:805:1): (debug):_updateCookieData([object Object]) execTime: 102295`
4. Settings backup: [file](http://s000.tinyupload.com/index.php?file_id=90101197882474842400)

**Comment by vanowm** [comment]
So far I'm unable to reproduce it with any of the cookies for ft.com or linkedin.com. Anything set to read-only stays read-only. (although I don't have **ft_access_c** cookie, perhaps it requires registration?)
Try restart the browser and see if any errors shown in browser console (read-only feature initialized only on browser start)

**Comment by SergeGardien** [comment]
Pardon me, you probably need to get to an FT article form Google (you need it as a referrer to get the possibility to read the article and get the ft_access_c cookie).
I haven't seen any error in the browser console.

Moreover:
1. I've tried with a clean Firefox Profile (no addons apart from CM+) and still, I have the same issue. That's odd.
2. Where do you store the read-write/read-only parameter in the cookies.sqlite file?
   I've checked it and I haven't seen any SQL-DB column storing it. I've seen only these columns:
   `id
   baseDomain
   originAttributes
   name
   value
   host
   path
   expiry
   lastAccessed
   creationTime
   isSecure
   isHttpOnly
   appId
   inBrowserElement`
3. I've also inspected the cookies.sqlite file before/after closing Firefox (with and without modifying the read-write option) and I haven't seen any change in the sqlite file.
4. I've created a cookie with CM+ with the same values of ft_access_c and read-only value for "content" and I called it ft_access_c1. Still, the read-only option is turned back to read-write soon as I restart FF.
5. Even if it is not CM+ related, would you mind suggesting me another addon with the feature to make read-only a specific cookie? I'd like to see if I have the same issue. EditThisCookie addon for Chrome works fine but it doesn't work at all once added to Firefox via "Chrome Store Foxified" addon.

**Comment by SergeGardien** [comment]
Pardon me, you probably need to get to an FT article form Google (you need it as a referrer to get the possibility to read the article and get the ft_access_c cookie).
I haven't seen any error in the browser console. Moreover I've tried with a clean Firefox Profile (no addons apart from CM+) and still, I have the same issue.

That's odd.

Even if it is not CM+ related, would you mind suggesting me another addon with the feature to make read-only a specific cookie? I'd like to see if I have the same issue.

**Comment by SergeGardien** [comment]
In the end I've found a solution to my problem by writing a javascript for greasemonkey which resets the cookie to the original value every time it is modified by the website.

Anyway, given that this is not an optimal solution (the cookie gets written by the website each time I open a page and I overwrite that cookie), if you find the source of the issue for my problem please, keep me posted.

Thanks

**Comment by vanowm** [comment]
The read-only information is stored in cookiesManagerPlus.json file in your profile directory.
Perhaps the file is not writable by firefox anymore? If so, try to delete the file.

I haven't seen any addon's with read-only cookies feature.

> Anyway, given that this is not an optimal solution (the cookie gets written by the website each time I open a page and I overwrite that cookie)

Actually that's how read-only works with CM+ anyway...

**Comment by SergeGardien** [comment]
No luck with the cookiesManagerPlus.json file. I've deleted it but the issue remains.

That's fine, my greasemonkey javascript is working fine.

Thanks again for the help Vanowm

**Comment by vanowm** [comment]
I can now reproduce it myself. The readonly data is not being saved at all.
For unknown reason JSON.stringify at [line 706 in coomanPlusCore.jsm](https://github.com/vanowm/FirefoxCookiesManagerPlus/blob/af18ee4640bdb61a15150856462880f48c8be736/src/chrome/modules/coomanPlusCore.jsm#L706) returns empty readonly object.

For debug added  two lines:

```
log(data.readonly, 1);
log(JSON.stringify(data.readonly));
```

It returned:

```
CM+ (coomanPlusCore.jsm:709:1): (object):
CU61t4JuyExUKrAuZj0Ekg== (object): [object Object]
{
    expires (number): 1666350653
}

 ----------
CM+ (coomanPlusCore.jsm:710:1): (string):[]

```

WHAT THE F@???

[EDIT]
Turned out the problem is that JSON cannot stringify correctly named objects inside an array and [line 30](https://github.com/vanowm/FirefoxCookiesManagerPlus/blob/af18ee4640bdb61a15150856462880f48c8be736/src/chrome/modules/coomanPlusCore.jsm#L30) incorrectly set readonly as array instead of named object by default.

**Comment by SergeGardien** [comment]
Good, thanks Vanowm.
I've tried to install the 1.13.2 xpi file from Firefox => Tools => Add-Ons but it doesn't give any response and the addon doesn't get installed.
Before asking in the Mozilla Forum, can you please confirm you've signed the xpi file? That could be a possible cause.

**Comment by vanowm** [comment]
Developers are no longer able sign their addons. Only mozilla can.
I just tried use their [official](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign) tutorial and what it did basically uploaded new version to mozilla and gave me this:

> Your add-on has been submitted for review. It passed validation but could not be automatically signed because this is a listed add-on.
> JPM [info] FAIL

Oh and it also disabled previously uploaded v1.13.2 that was in a queue for review. Now I have to somehow contact them and hope they can re-enable that version or upload new version and go back of the queue... (there were 108 addons in the queue)

**Comment by SergeGardien** [comment]
I see. Please keep me/us posted by updating this issue thread or by creating a new one.
Thanks

**Comment by vanowm** [comment]
v1.13.2 is available at https://addons.mozilla.org/firefox/addon/cookies-manager-plus/ and via auto update in Firefox.

**Comment by SergeGardien** [comment]
Many thanks for the continued effort Vanowm, now it works.

**Comment by SergeGardien** [comment]
Hi Vanowm, I reopen this issue because somehow Cookies Manager+ always starts the Firefox "Browser Console" windows at startup.
If I disable Cookies Manager+ instead the "Browser Console" doesn't appear.

Is there a way to disable the CM+ debug mode?

**Comment by vanowm** [comment]
CM+ options -> general tab -> debug level dropdown, uncheck debug checkbox.

**Comment by SergeGardien** [comment]
Yes, I know that but I wasn't able to uncheck that checkbox. Anyway, I've tried to remove completely CM+ and reset its settings and now I've been able to uncheck the debug box.

All is working fine.

Thanks again :)

**Comment by vanowm** [comment]
What do you mean you were not able uncheck that checkbox? The only checkbox you shouldn't be able uncheck is the "Errors" checkbox.

**Comment by SergeGardien** [comment]
In my case the only checked box was the debug one, the other two (errors included) where unchecked. That's why I was asking how to disable the debug mode.

Actually everything started on its own and suddenly I've begun to see the browser console at Firefox startup. This went on for few weeks before an eureka moment (the only time I've used the browser console has been when you suggested it to me to check the problem mentioned in this thread). Hence I've decided to disable CM+ and I've seen the browser console disappearing.

I guess there has been a conflict somewhere in Firefox/CM+/other addons, hence the checked (and uncheckable) debug mode.

**Comment by vanowm** [comment]
Still not clear, were you unable uncheck the debug checkbox at all? Or you could uncheck it, but console would still popup even with ALL checkboxes unchecked?

_I just want get to the bottom of it, weather it's something wrong in the addon, which needs to be fixed (I'm unable to reproduce myself so far) or it was a user error_

**Comment by SergeGardien** [comment]
> were you unable uncheck the debug checkbox at all?

Correct

> I just want get to the bottom of it, weather it's something wrong in the addon, which needs to be fixed (I'm unable to reproduce myself so far) or it was a user error

Cannot say much on either but I haven't opened the CM+ preference/settings for a long time and the issue appeared out of the blue. I don't know what caused it but I've solved by resetting the addon.
I'm sorry I cannot be more helpful.

In case it happens again I'll tell you so we can investigate while the issue is still in place.
