### ISSUE TITLE
Blank window - search doesn't work - unable to pull up any cookies

### ISSUE THREAD

**Issue by Louiscar1** [vanowm/FirefoxCookiesManagerPlus#135]
Just loaded this and couldn't do anything with it. Only cookie it brings up is when you choose to view the cookie for the site you are currently on.
Otherwise I get a blank screen by default and nothing works for the search bar.

Os: Windows 7 Ultimate
FF: 43.0.1

following your instructions regarding the debug option I find that when I click the debug in options and close the options immediately the error console pops up with a lot of CM+ messages, It is not practical to copy these as there is no bulk copy option, you have to it line by line.
So I am using the normal console and posting what is in there  after clearing it down, hitting debug and opening the normal console.

[console for cm_plus.txt](https://github.com/vanowm/FirefoxCookiesManagerPlus/files/1163105/console.for.cm_plus.txt)

**Comment by vanowm** [comment]
The provided logs have no useful data...
I don't know what is "normal console", browser console is when you press CTRL + SHIFT + J
There you can click at the beginning of the text you want to copy and then scroll to the end and while holding SHIFT key click again, it will select the text between two clicks.
(don't need any CSS or Net logs)

Anyway, I can reproduce it on FF43 myself, so no need for the logs

Thanks for the report.

**Comment by Louiscar1** [comment]
Error console is what popped up  not the one that comes up with CTRL + SHIFT +J
In that one you cannot copy all the entries but they looked more like error messages you'd want to see. Don't know confused about these 2 consoles.

Glad you reproduced it. Curiously FF after I installed another plugin decided to suddenly update itself without my permission. So I'm no longer on 43 it went to 47. I haven't tried CM+ yet on that one but will do in a bit

**Comment by vanowm** [comment]
Sounds like the Console2 addon..which also allows select multiple lines when holding SHIFT key, or select all via CTRL+A
Anyway, this bug seems to be affecting FF45 and older.
P.S.
If you are holding on to FF43 because it allows use extensions without mozilla's signature, then you might want to try FF52 ESR, it only updates with security patches.
