### ISSUE TITLE
sorting the exception-list didn't work properly, requesting: filter-featuer for exception-list

### ISSUE THREAD

**Issue by LutzL** [vanowm/FirefoxCookiesManagerPlus#136]
great add-on! thx

I wan't to remove an exception, but have difficulties to find the URL in the exception-list.

I click 'name' in the title and expect the list is sorted alphabetically after this, but somehow it is sorted but not properly. Two times it goes from 0-a-z and then again 0-a-z.

My exception-list is long 200-300 or so.
It cost me too much time to manually scan the complete list to find the item i want.

I think it would be a good idea to add a filter-feature to that list.

Versions:
Linux
Firefox ESR 52.2.0 64bit
Cookies Manager+ 1.14.2

**Comment by LutzL** [comment]
OK i think the problems comes from list entries beginning with a dot.
i want to remove '.youtube.com' it's not listed *Bug#2?*

my default is to NOT ACCEPT cookies at all.

in the past i allowed .youtube.com to set cookies.

if i try to add a new 'block' entry for this url, it is shown in the list.
but the cookies are not blocked.

I can come around this evening again.
THX in advance

**Comment by vanowm** [comment]
CM+ has no control over exceptions window and it's functionality.

When you use CM+ to delete and block cookie, it uses built-in [nsICookieManager.remove()](https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager#remove()) function with "block" flag, what and how browser block the cookies is beyond CM+ control.
You probably want to file a bug report at [Bugzila](https://bugzilla.mozilla.org/)
