### ISSUE TITLE
Restore Blocked Cookies

### ISSUE THREAD

**Issue by gwmolitor** [vanowm/FirefoxCookiesManagerPlus#139]
How does one unblock BLOCKED cookies when no cookie backup is available?
For Firefox 52 in Windows 10
Some how I must have blocked a gmail cookie because gmail thinks I have cookies disabled which I don't.
Cookies Manager + does not seem to have a Restore Blocked Cookies option.
Is there a file where blocked cookies are stored?

**Comment by vanowm** [comment]
CM+ -> Tools -> Exceptions

Or 

Browser's options -> Privacy & Security -> Accept cookies from websites -> Exceptions

**Comment by gwmolitor** [comment]
Thank you.
