### ISSUE TITLE
Highlight CookiesManager+ in FF Tools menu -> FF CRASH

### ISSUE THREAD

**Issue by SDB69100** [vanowm/FirefoxCookiesManagerPlus#141]
Hi V@no

I still use your add-on as I didn't upgrade Firefox for Mac. It's very useful but will it be possible to get a very last version that make possible to hide CookiesManager+ from Tools menu ? Firefox instantly crashes when I cross this menu with the mouse and reach your add-on item. It doesn't happen at all when I launch CookiesManager+ from the bar (that's what I do). But I often need to manage with others extensions that are only launchable via the Tools menu. Will it be possible to still have the CM+ icon in the bar if CM+ is hidden in Tools ? If not, can you just turn this CM+ item into a "single" one (non expandable, no submenu) that may prevent this crash ?

Thank you for paying attention to this report and request.

**Comment by vanowm** [comment]
What FF version? To be honest, I don't see any reasons support any versions of FF, that browser is dead to me.

Perhaps try [Waterfox](http://waterfoxproject.org/)

**Comment by SDB69100** [comment]
48.0.2 version for Mac. I understand what you say. I haven't updated FF for years but I still use this app and last supported version on a macbook pro under Snow Leopard. My request is the only one for me, I don't see any problem with Cookies Manager+ thank you for Waterfox I'll give it a try.
________________________________
De : V@no <notifications@github.com>
Envoyé : lundi 19 novembre 2018 05:28
À : vanowm/FirefoxCookiesManagerPlus
Cc : SDB69100; Author
Objet : Re: [vanowm/FirefoxCookiesManagerPlus] Highlight CookiesManager+ in FF Tools menu -> FF CRASH (#141)


What FF version? To be honest, I don't see any reasons support any versions of FF, that browser is dead to me.

Perhaps try Waterfox<http://waterfoxproject.org/>

**Comment by vanowm** [comment]
If it helps, you could try remove it yourself:
Just remove whole <menuitem> section starting from this line:
https://github.com/vanowm/FirefoxCookiesManagerPlus/blob/876f66c648fe13c0584b8f5daca70d933c878486/src/chrome/content/sysOverlay.xul#L51

**Comment by SDB69100** [comment]
Done. Thank you for having helped ! It worked with FF 47.0.1
Bye Vano

Le 20 nov. 2018 05:20, "V@no" <notifications@github.com> a écrit :

If it helps, you could try remove it yourself:
Just remove whole section starting from this line:
https://github.com/vanowm/FirefoxCookiesManagerPlus/blob/876f66c648fe13c0584b8f5daca70d933c878486/src/chrome/content/sysOverlay.xul#L51
