### ISSUE TITLE
Can't protect cookies

### ISSUE THREAD

**Issue by Bisaloo** [vanowm/FirefoxCookiesManagerPlus#47]
The 'protect' button has no effect. The displayed status (Protected/Unprotected) doesn't change and neither does the actual status (ie cookies are not protected).

FF 38.0
Ubuntu 14.04

**Comment by vanowm** [comment]
It's due to CookieCuller is no longer working. I'm working on a support for CookieKeeper
https://addons.mozilla.org/firefox/addon/cookiekeeper
