### ISSUE TITLE
Can't restore cookies

### ISSUE THREAD

**Issue by joergma** [vanowm/FirefoxCookiesManagerPlus#48]
When I try to restore all cookies on an other machine, they are shown
but never imported. They disappear after about 2 seconds:

![2015-09-03-17-12-18](https://cloud.githubusercontent.com/assets/14111597/9662350/66cb8230-525f-11e5-8c3d-fed263f2f1cc.png)

On both machines:
FF 40.0.3
Win 7 x64 Pro

**Comment by vanowm** [comment]
Anything in error console? (CTRL + SHIFT + J)

**Comment by joergma** [comment]
Nothing in error console. It was the Add-on "Self-Destructing Cookies 0.4.7.1". After white-listing the cookie domains (from the cookies to be restored) in that addon, the restoring has worked flawlessly.
