### ISSUE TITLE
No source on GitHub

### ISSUE THREAD

**Issue by rugk** [vanowm/FirefoxCookiesManagerPlus#49]
I'm quite surprised you only use this repo for issue tracking and [your (uncompleted) Github page](https://vanowm.github.io/FirefoxCookiesManagerPlus/). Why don't you also host the source code at GitHub?
I know [you can view it at Mozilla](https://addons.mozilla.org/en-US/firefox/files/browse/218428/), but to have a real repo would be better.
Additionally at Mozilla no license information is given. So it would also be good to know what license applies to this.

**Comment by rugk** [comment]
BTW labels are not really intended to be used as "fixed". Instead of this you can e.g. close issues [via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/) or Pull Requests.

**Comment by vanowm** [comment]
Nice!
didn't know about that.
Thank you.
