### ISSUE TITLE
Cookie = File menu?

### ISSUE THREAD

**Issue by rugk** [vanowm/FirefoxCookiesManagerPlus#51]
![file](https://cloud.githubusercontent.com/assets/11966684/10555048/c8dbfb0e-7469-11e5-8f15-8c0b7fa052ba.png)

I think this menu should be named 'Cookie' or 'Cookies' instead of 'File' as file is way to inaccurate.

**Comment by vanowm** [comment]
That menu is for working with files, so it's more accurate then "cookies" which the whole window is for.

**Comment by rugk** [comment]
But AFAIK the File -> Add button adds a new cookie and not a file... :wink:

**Comment by vanowm** [comment]
I agree, "Add" is kind of odd, if anything it should be renamed to "New", which will be appropriate and intuitive because majority if not all applications have File menu -> New that creates new document or such.

**Comment by vanowm** [comment]
Merged to #55

**Comment by rugk** [comment]
> Merged to #55

Rather "moved", but I know what you mean... 😊
