### ISSUE TITLE
View -> Always on top Not works

### ISSUE THREAD

**Issue by zlietapki** [vanowm/FirefoxCookiesManagerPlus#53]
Feature "View -> Always on top" is not working. It's possible to switch to any other firefox window.
42.0 Mozilla Firefox for Ubuntu

**Comment by vanowm** [comment]
I'm unable test it on other systems but Windows, so if you would, can you test this for me:
in **{bb6bc1bb-f824-4702-90cd-35e2fb24f25d}\chrome\content\cookiesmanagerplus.js** find:
`xulWin.zLevel = (coomanPlus.prefTopmost) ? xulWin.raisedZ : xulWin.normalZ`
Replace it with
`xulWin.zLevel = (coomanPlus.prefTopmost) ? xulWin.highestZ : xulWin.normalZ`

If it still doesn't work, then Firefox itself doesn't allow such feature.

Thanks.

**Comment by vanowm** [comment]
It seems only Windows OS supports zLevel flag therefore I'm forced to remove this option for non-windows systems.

**Comment by vanowm** [comment]
commit 23b1f42
