### ISSUE TITLE
Remove cookies button doesn't work anymore?

### ISSUE THREAD

**Issue by grenzor** [vanowm/FirefoxCookiesManagerPlus#59]
This is a great addon but it seems in the newest Firefox 45 the remove cookies button doesn't clear anything. Manually going to do the manager and deleting works but not the button.

**Comment by vanowm** [comment]
Can't reproduce, works for me.
Any error messages in console?

**Comment by grenzor** [comment]
My bad, it is working seems my comp was acting up and after a restart it works fine.

On a completely different issue, it seems in total private browsing (pb mode, never remember history) adding a cookie does not work. I can try adding it via the manager but observing headers you can see it doesn't add them. Is there a reason for this/something I'm missing? With history and other options enabled it works fine.

**Comment by vanowm** [comment]
Please start a new topic, so if someone has the same problem they can follow.

P.S.
again, can't reproduce, please provide more details how to reproduce the issue.
