### ISSUE TITLE
Completely broken on firefox 46+

### ISSUE THREAD

**Issue by mzso** [vanowm/FirefoxCookiesManagerPlus#61]
Hi!
It doesn't show any cookies starting with 46 beta. E10s on and off.

**Comment by vanowm** [comment]
Works on my system and no errors in console.
![Imgur](http://i.imgur.com/6aGRDQo.png)

What is your system and is there anything useful in the error console?

**Comment by mzso** [comment]
I get this when opening the window on central:

```
unreachable code after return statement[További tudnivalók]export.js:42:1
SyntaxError: missing ] after element listexport.js:551:41
TypeError: coomanPlus.prefTemplateClipboard is undefined
coomanPlus.onPrefChange.do()
cookiesmanagerplus.js:563
coomanPlus.start()
cookiesmanagerplus.js:420
coomanPlus.load()
cookiesmanagerplus.js:228
onload()
cookiesmanagerplus.xul:1
this.Utils.openWindow()
utils.jsm:147
this.Utils.prompt()
utils.jsm:280
sm_restorePrompt()
SessionManagerHelper.js:744
sm_check_for_crash()
SessionManagerHelper.js:679
SessionManagerHelper.observe()
SessionManagerHelper.js:243
SessionStartup.prototype._onSessionFileRead()
nsSessionStartup.js:135
bound ()
self-hosted
Handler.prototype.process()
Promise-backend.js:937
this.PromiseWalker.walkerLoop()
Promise-backend.js:816
bound ()
self-hosted
bound bound ()
self-hosted
cookiesmanagerplus.js:563:45
```

**Comment by BondiBear** [comment]
refresh broken on ff46

**Comment by mzso** [comment]
It still doesn't show any cookies for me on FF47 Beta.

**Comment by vanowm** [comment]
Might have been fixed in v1.7.2b1 e41d77c

**Comment by mzso** [comment]
It works. It just seems that anything I do with it hangs firefox for a minute or so: Opening it's window, searching, deleting cookies, scrolling.

**Comment by mzso** [comment]
It seems to work much better now with b2. There's only a few seconds delay before the cookies are shown. Also opening and closing the windows doesn't hang firefox for a minute+.
