### ISSUE TITLE
Unable to delete cookies whatsoever

### ISSUE THREAD

**Issue by dkichler** [vanowm/FirefoxCookiesManagerPlus#66]
Since upgrading to 1.7.1, I've been unable to delete cookies at all.  At first I thought it was a multi-select problem, but it appears to be affecting single selection/delete as well.  The behaviour I experience:
- select a bunch of cookies
- hit delete button
- hit confirmation to "delete all"
- nothing happens

Same behaviour for deleting a single cookie.

My specs: OS X 10.11.4,  FF 46.0.1, Cookies Manager 1.7.1

**Comment by vanowm** [comment]
Try change **extensions.cookiesmanagerplus.debug** to 7, open browser console (on max it's probably Command + SHIFT + J), open CM+, select cookies (it will flood the console with messages), clear the console and try delete cookies, see if anything error messages shown in the console.

**Comment by dkichler** [comment]
I will assume that you meant **extensions.cookiesmanagerplus.debug** (extensions.cookiesmanagerplus.debug was not present, presumably b/c I don't have that extension).  However, following those instructions, I see nothing printed to the console when I select or attempt to delete any cookies.

**Comment by vanowm** [comment]
ops...sorry about that, yes, extensions.cookiesmanagerplus.debug
When that preference set to 7 it should switch into debug mode and start printing almost every action it does to the console. If nothing shows, then perhaps it failed on browser startup, in which case try to restart browser and see if any errors shows in the console then.

**Comment by JerryWho** [comment]
Hi, same problem here. MacOS X 10.9.5
That's the output of the debug-log:
https://gist.github.com/JerryWho/43b6d2fe139d3e80cb7216942df32079

**Comment by vanowm** [comment]
What if you disable strict mode?
about:config -> javascript.options.strict

**Comment by JerryWho** [comment]
Here's the log without strict mode:
https://gist.github.com/JerryWho/694834e7f489a82918462659183d4194

**Comment by vanowm** [comment]
Fixed in v1.8
