### ISSUE TITLE
firefox 46.0.1 (64 bit)

### ISSUE THREAD

**Issue by mapx-** [vanowm/FirefoxCookiesManagerPlus#67]
Does not work in FF 46.0.1 (64-bit)
error:

TypeError: m is null
menu()
 sysOverlay.js:78
onpopupshowing()
 browser.xul:1
 sysOverlay.js:78:4

error on this row:
            m.label = this.strings.site + ": " + host;

**Comment by mapx-** [comment]
probably the same issue here:
https://github.com/vanowm/FirefoxCookiesManagerPlus/issues/62

**Comment by vanowm** [comment]
Fixed in [v1.7.2b2](https://github.com/vanowm/FirefoxCookiesManagerPlus/blob/main/src/chrome/content/sysOverlay.js#L75)
