### ISSUE TITLE
Extension has been removed?

### ISSUE THREAD

**Issue by lino10** [vanowm/FirefoxCookiesManagerPlus#69]
Hi, today I want to install the Cookies Manager+, but it seems that the extension is no longer exists in AMO?
https://addons.mozilla.org/en-US/firefox/addon/cookies-manager-plus/

> This add-on has been removed by its author.

**Comment by Alhaitham** [comment]
+1

**Comment by vanowm** [comment]
It has been suspended until I find time update it to usable state.

**Comment by vanowm** [comment]
extension is live now, hopefully v1.8 will work better. I had to remove completely HTML5 support
