### ISSUE TITLE
Cookies Mgr+ 1.8 deleting cookies not working on Mac

### ISSUE THREAD

**Issue by 9jkh** [vanowm/FirefoxCookiesManagerPlus#70]
Title says it all
FF 45.1.1 ESR/Mac 10.8.5

**Comment by vanowm** [comment]
Please change **extensions.cookiesmanagerplus.debug** in about:config to 7 and post what it shows in error console when you try to delete a cookie.

**Comment by 9jkh** [comment]
Not finding the "error console" specifically. I'm not all that familiar with the different tools in Web Developer. 

Screenshot attached. Not sure this is what you want, but after trying a number of different options, it was the only logging that occurred when I tried deleting a cookie.
(about:config changed from 1 to 7)

Also, maybe some other about:config setting is responsible for the not deleting? See second screenshot below. Have a look at "delete expired" and "delete protected." Nope, changed from false to true. Made no difference. Although going from false to true automatically removed a number of expired cookies, still can't manually delete a cookie.

CM+ (cookiesmanagerplus.js:388:1): (debug):cookieSelectedEvent() execTime: 1467526
CM+ (cookiesmanagerplus.js:1241:1): (debug):[,true] cookieSelected() execTime: 1467527
CM+ (cookiesmanagerplus.js:534:1): (debug):[deleteExpired: false] loadCookies() execTime: 1467527
CM+ (treeUtils.js:42:1): (debug):[sort begin] sortTreeData() execTime: 1467532
CM+ (treeUtils.js:102:1): (debug):[sort end] sortTreeData() execTime: 3 [1467535]
CM+ (cookiesmanagerplus.js:1151:1): (debug):selectLastCookie() execTime: 1467537
CM+ (cookiesmanagerplus.js:388:1): (debug):cookieSelectedEvent() execTime: 1467539
CM+ (cookiesmanagerplus.js:1241:1): (debug):[,false] cookieSelected() execTime: 1467539
CM+ (cookiesmanagerplus.js:1241:1): (debug):[,false] cookieSelected() execTime: 1467544
CM+ (cookiesmanagerplus.js:1241:1): (debug):[,false] cookieSelected() execTime: 1467548

![screen shot 2016-05-19 at 4 16 32 pm](https://cloud.githubusercontent.com/assets/10210828/15408391/fdd070ce-1ddd-11e6-87dc-515f37a4a0c1.png)

![screen shot 2016-05-19 at 4 28 24 pm](https://cloud.githubusercontent.com/assets/10210828/15408573/e6a5a170-1dde-11e6-8687-8e6f0ee9de59.png)

**Comment by vanowm** [comment]
That's the correct console. However theres no entries regarding deleting cookies at all. How are you deleting it? Del key, via edit menu, right click?

P.s. sorry for all the questions but I don't have access to a computer right now and can't test it myself.

**Comment by 9jkh** [comment]
From right-click, the delete radio button at bottom, or from Edit menu, I get the "are you sure" message, but nothing happens.

**Comment by vanowm** [comment]
Ok, now that I had chance test it, it works fine on Windows 7/10, there is no "are you sure" dialog but there is a confirmation dialog:
![delete confirmation dialog](http://i.imgur.com/XmWCNxq.png)

After I click on "Delete" button at that dialog I get this in the browser console:

```
CM+ (cookiesmanagerplus.js:388:1): (debug):cookieSelectedEvent() execTime: 43022168
CM+ (cookiesmanagerplus.js:1241:1): (debug):[,true] cookieSelected() execTime: 43022169
CM+ (commonFunc.js:261:1): (debug):[normal cookie] cookieRemove() execTime: 43022169
CM+ (cookiesmanagerplus.js:534:1): (debug):[deleteExpired: false] loadCookies() execTime: 43022170
CM+ (treeUtils.js:42:1): (debug):[sort begin] sortTreeData() execTime: 43022289
CM+ (treeUtils.js:102:1): (debug):[sort end] sortTreeData() execTime: 1 [43022291]
CM+ (cookiesmanagerplus.js:1151:1): (debug):selectLastCookie() execTime: 43022291
CM+ (cookiesmanagerplus.js:388:1): (debug):cookieSelectedEvent() execTime: 43022291
CM+ (cookiesmanagerplus.js:1241:1): (debug):[,false] cookieSelected() execTime: 43022291
CM+ (cookiesmanagerplus.js:781:1): (debug):_updateCookieData() execTime: 43022293
CM+ (cookiesmanagerplus.js:1241:1): (debug):[,false] cookieSelected() execTime: 43022294
CM+ (cookiesmanagerplus.js:781:1): (debug):_updateCookieData() execTime: 43022295
```

Almost the same as yours, except third line shows executing cookieRemove function, yours doesn't. So it's possible on Mac Firefox works differently when it comes to dialog boxes (?) in which case I'll need Mac users help to find what exactly is the problem.

**Comment by vanowm** [comment]
Found a way to reproduce it on Windows. Will be fixed with next update.

**Comment by 9jkh** [comment]
OK good to hear. Thanks.
