### ISSUE TITLE
Name, Domain and Path should not be allowed to be changed when editing multiple cookies

### ISSUE THREAD

**Issue by vanowm** [vanowm/FirefoxCookiesManagerPlus#76]

**Comment by emilhem** [comment]
I use 1.11.2 and I can't edit multiple sites domain, name nor path.
Firefox ESR 45.2.0
Debian Jessie

**Comment by vanowm** [comment]
That is by design, hens this issue created and fixed ;)

**Comment by emilhem** [comment]
Ah, I read it wrong... :/

Why may I ask? It is really useful.

**Comment by vanowm** [comment]
Because of complications it will create. See, these 3 fields of data determine uniqueness of a cookie, which means if all 3 fields set to the same value for multiple cookies, these cookies become as one single cookie. I guess I could add a warning message.

If you want, please start a new topic to add it as a new feature, make it easier to track.
