### ISSUE TITLE
E10s support

### ISSUE THREAD

**Issue by juhiyu** [vanowm/FirefoxCookiesManagerPlus#81]
Hellos, I want to ask if E10s support is planned or already implemented (couldn't figure out from install.rdf). I think e10s is soon released in Firefox 48 or 49 so would be good to have compatibility

**Comment by vanowm** [comment]
Using FF nightly (50.0a1) with e10s forced enabled, haven't noticed any issues.

P.S.
Now that you mentioned this, one of the reasons why v1.7 worked so well on my system and horrible on others, could be because of e10s enabled (?)

**Comment by juhiyu** [comment]
That may be a reason.

I see Firefox has listings of addons (arewee10syet.com) in terms of e10s as fully compatible and shimmed (compatible but may cause performance or other issues). also heard firefox is only rolling out e10s to users if they know that their addons fully support e10s...perhaps best to tell firefox?

**Comment by vanowm** [comment]
I've never seen that website before, and frankly I have no idea what they are talking about. What "it works" or "report bug" links they are referring to?

**Comment by juhiyu** [comment]
I am not a developer so unfortunately i cannot provide much details but Mozilla tells addon developers to refer to this to see how current addons can become e10s compatible: https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox
