### ISSUE TITLE
Something wrong with v1.10.1

### ISSUE THREAD

**Issue by gameclamp** [vanowm/FirefoxCookiesManagerPlus#84]
I restore some cookies from Netscape HTTP Cookie File,CM+ say "Successfully restored 7 cookie(s)",but only 3 cookies visible.
v1.9.1 work find.

**Comment by vanowm** [comment]
I could think of 3 possibilities that is not a bug:
1. search field is not empty, and only 3 cookies matching the search criteria
2. some cookies in the file have the same domain, path and name. Restore routine doesn't check for duplicates.
3. this is most likely: the other 4 cookies are expired

If none of these applied to your case and your cookie file doesn't have any sensitive information, please post it here so I could test it as well.

Thank you.

**Comment by gameclamp** [comment]
I found that the disappeared cookies like this,it should be expire at the session end
`abc.com    FALSE   /   FALSE       CID xxxxxxxxxxxxxxx`
the others like this
`abc.com    FALSE   /   FALSE   1465993958  loginType          1`

**Comment by vanowm** [comment]
Hmmmm it seems I can't even add or change session cookies either.
