### ISSUE TITLE
GUI displays some Cookie values in a “binary” form in the bottom panel

### ISSUE THREAD

**Issue by sebalis** [vanowm/FirefoxCookiesManagerPlus#89]
I noticed this while developing a little web application that sets a random string from the alphabet [A-Za-z0-9]. My strings get displayed in a form that is probably an attempt at decoding the original value in some way. (I am saying this because I have noticed other cookies whose string value is a JSON object in encoded form: if I switch on the “Content” column in the list I see that JSON string in URL-encoded format, but if I select the cookie then the details panel below the list shows the same value in readable form.)

The problem with my own cookie is that the value is just a random string that should not be decoded. The current value is “tucvVwYb4hEhG1uZ74vJK3e0sIiAlrcyNsm8ru4I”, but the content panel shows it as a string that looks like a bad representation of some binary value. Several other cookies have the same problem. See the screenshot, where I blacked out the site and cookie name for anonymity. You can create a cookie yourself using the value I pasted here in order to reproduce the problem. If double-click the cookie and cancel the edit dialog, the value is actually shown correctly, but the display always reverts back to the incorrect form.

This is using Firefox 47.0 on Linux by the way.

![cookies-manager-decoded-value](https://cloud.githubusercontent.com/assets/8028279/16170589/15764e56-3558-11e6-9234-dae9e6829e66.png)

**Comment by vanowm** [comment]
This was fixed in [v1.11.2](https://github.com/vanowm/FirefoxCookiesManagerPlus/commit/b4480ef998cae049b041bd2d7c9057182be2a57a)

**Comment by sebalis** [comment]
You’re right! Apologies for not checking this before reporting, and thanks.
