### ISSUE TITLE
Add an option to use old menu entry Tools > CMP

### ISSUE THREAD

**Issue by jay** [vanowm/FirefoxCookiesManagerPlus#91]
FF 49.0a2 and CMP 1.11.2

Older versions of CMP I could open it by Tools > CMP. Now that is a sub-menu so I have to do Tools > CMP > CMP. My suggestion is an option for the old way so one could do Tools > CMP

Also the icon is missing in the tools menu

**Comment by vanowm** [comment]
You can click on Tools > CMP and it will open CMP as before. Submenu provides additional options.

Created #92 for the icon issue. Thanks.
